const ingredientsList = [
  'Apple',
  'Banana',
  'Carrot',
  'Dates',
  'Eggplant',
  'Fig',
  'Garlic',
  'Honey',
  'Tomato',
  'Lemon',
  'Lime',
  'Orange',
  'Pear',
  'Cherry',
  'Strawberry',
  'Kiwi',
  'Peach',
  'Plum',
  'Mango',
  'Blueberry',
  'Blackberry',
  'Raspberry',
  'Watermelon',
  'Cucumber',
  'Lettuce',
  'Spinach',
  'Kale',
  'Broccoli',
  'Cauliflower',
  'Potato',
  'Sweet Potato',
  'Onion',
  'Bell Pepper',
  'Chili Pepper',
  'Mushroom',
  'Corn',
  'Peas',
  'Asparagus',
  'Zucchini',
  'Pumpkin',
  'Celery',
  'Avocado',
  'Olive',
  'Chicken',
  'Beef',
  'Pork',
  'Lamb',
  'Turkey',
  'Duck',
  'Fish',
  'Salmon',
  'Tuna',
  'Shrimp',
  'Crab',
  'Lobster',
  'Mussels',
  'Oysters',
  'Scallops',
  'Rice',
  'Pasta',
  'Bread',
  'Flour',
  'Sugar',
  'Butter',
  'Milk',
  'Cheese',
  'Eggs',
  'Quinoa',
  'Couscous',
  'Barley',
  'Basil',
  'Parsley',
  'Cilantro',
  'Dill',
  'Rosemary',
  'Thyme',
  'Sage',
  'Oregano',
  'Mint',
  'Chives',
  'Green Beans',
  'Brussels Sprouts',
  'Artichoke',
  'Leek',
  'Fennel',
  'Red Cabbage',
  'Bok Choy',
  'Arugula',
  'Endive',
  'Radicchio',
  'Beetroot',
  'Radish',
  'Turnip',
  'Squash',
  'Okra',
  'Jicama',
  'Parsnip',
  'Sunflower Seeds',
  'Pumpkin Seeds',
  'Sesame Seeds',
  'Almonds',
  'Walnuts',
  'Pecans',
  'Cashews',
  'Pine Nuts',
  'Peanuts',
  'Hazelnuts',
  'Macadamia Nuts',
  'Chestnuts',
  'Sun-Dried Tomatoes',
  'Capers',
  'Olives',
  'Pickles',
  'Jalapeno',
  'Serrano Pepper',
  'Habanero Pepper',
  'Ghost Pepper',
  'Scotch Bonnet',
  'Poblano',
  'Soy Sauce',
  'Hot Sauce',
  'Worcestershire Sauce',
  'BBQ Sauce',
  'Sriracha',
  'Ketchup',
  'Mustard',
  'Mayonnaise',
  'Horseradish',
  'Tahini',
  'Pesto',
  'Alfredo Sauce',
  'Marinara Sauce',
  'Bolognese Sauce',
  'Carbonara Sauce',
  'Gorgonzola',
  'Parmesan',
  'Mozzarella',
  'Cheddar',
  'Swiss Cheese',
  'Brie',
  'Camembert',
  'Feta',
  'Gouda',
  'Havarti',
  'Provolone',
  'Ricotta',
  'Roquefort',
  'Stilton',
  'Tofu',
  'Tempeh',
  'Seitan',
  'Chickpeas',
  'Lentils',
  'Black Beans',
  'Kidney Beans',
  'Pinto Beans',
  'Navy Beans',
  'Lima Beans',
  'Edamame',
  'Falafel',
  'Hummus',
  'Maple Syrup',
  'Agave Nectar',
  'Balsamic Vinegar',
  'Red Wine Vinegar',
  'Apple Cider Vinegar',
  'White Wine Vinegar',
  'Rice Vinegar',
  'Saffron',
  'Vanilla',
  'Cinnamon',
  'Nutmeg',
  'Cloves',
  'Ginger',
  'Turmeric',
  'Cumin',
  'Coriander',
  'Cardamom',
  'Paprika',
  'Cayenne Pepper',
  'Chili Powder',
  'Curry Powder',
  'Garam Masala',
  'Star Anise',
  'Fennel Seeds',
  'Mustard Seeds',
  'Poppy Seeds',
  'White Pepper',
  'Black Pepper',
  'Green Peppercorns',
  'Pink Peppercorns',
  'Szechuan Peppercorns',
  'Flax Seeds',
  'Chia Seeds',
  'Hemp Seeds',
  'Canola Oil',
  'Olive Oil',
  'Vegetable Oil',
  'Coconut Oil',
  'Sesame Oil',
  'Peanut Oil',
  'Sunflower Oil',
  'Grapeseed Oil',
  'Avocado Oil',
  'Lard',
  'Beef Tallow',
  'Chicken Fat',
  'Duck Fat',
  'Ghee',
  'Clotted Cream',
  'Heavy Cream',
  'Sour Cream',
  'Yogurt',
  'Buttermilk',
  'Kefir',
  'Skim Milk',
  'Whole Milk',
  '2% Milk',
  'Soy Milk',
  'Almond Milk',
  'Coconut Milk',
  'Rice Milk',
  'Oat Milk',
  'Hemp Milk',
  'Cashew Milk',
  'Macadamia Milk',
  'Pea Milk',
  'Lactose-Free Milk',
  'Condensed Milk',
  'Evaporated Milk',
  'Powdered Milk',
  'Chocolate Milk',
  'Eggnog',
]

export default ingredientsList
